#! /usr/bin/perl

# Copyright (c) 2024 Marc Espie <espie@openbsd.org>
# 
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

use v5.36;
use FindBin;
use Getopt::Std;
use lib "$FindBin::Bin/lib";
use TagVideos::Base;
use TagVideos::Path;
use locale;

my $opts = {};

if (!getopts('d:Ll', $opts) || @ARGV != 1) {
	TagVideos::Base->usage("[-Ll] [-d database ] filename");
}

my $dbpath = $opts->{d};
if ($opts->{l} && -r 'video_tags') {
	$dbpath //= 'video_tags';
}

my $db = TagVideos::Base->connect($dbpath, {ReadOnly => 1});

my $query = $db->prepare(qq{
	select tag from _filetag where path=? order by tag;});
my $tag;

my $path = $ARGV[0];
if (!$opts->{L}) {
	$path = TagVideos::Path->resolve_link($path);
}
$query->execute($path);
$query->bind_columns(\$tag);

my @tags;
while ($query->fetch) {
	push(@tags, $tag);
}
say "Tags: ", join(' ', @tags);
