.\" Copyright (c) 2024 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SEARCH-VIDEOS-TAGS 1
.Os
.Sh NAME
.Nm search-videos-tags
.Nd extract paths that contain some tags from the database
.Sh SYNOPSIS
.Nm
.Op Fl lIV
.Op Fl d Ar database
.Op Fl D Oo ! Oc Ns Ar descr
.Op Oo ! Oc Ns Ar tag ...
.Sh DESCRIPTION
Extract from the database all files that match all the tags given
as
.Ar tag
parameters and prints them to standard output.
.Pp
If a tag doesn't exist verbatim, the parameter will be used as a partial match,
.Pp
Prefixing a tag with ! will instead select files that do not match this tag.
.Pp
Using a lone ! as a search parameter will show paths that do not have any tags
defined.
.Nm
takes the following options:
.Bl -tag -width data
.It Fl d Ar database
Select another database instead of the default
.Pa $HOME/videos_tags .
.It Fl D Oo ! Oc Ns Ar descr
Filter by description.
.It Fl l
Look up for a local database, namely
.Pa video_tags
in the current directory, this supersedes env variable.
.It Fl I
Exclude paths matching static images and gif-like objects.
.It Fl V
Exclude paths matching videos.
.El
.Sh ENVIRONMENT
.Bl -tag -width DBPATH
.It Ev TAGVIDEOSDBPATH
Path to the database instead of the default
.Pa $HOME/video_tags
.El
.Sh FILES
.Bl -tag -width DBPATH
.It Pa $HOME/videos_tags
Default path to the
.Xr sqlite3 1
database .
.El
.Sh SEE ALSO
.Xr sqlite3 1 ,
.Xr tag-videos 1
.Sh AUTHORS
.An Marc Espie
