.\" Copyright (c) 2024 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt TAG-VIDEOS 1
.Os
.Sh NAME
.Nm tag-videos
.Nd interactive tag manager for use with mpv
.Sh SYNOPSIS
.Nm tag-videos
.Op Fl Lq
.Op Fl c Ar cwd
.Op Fl d Ar database
.Op Fl h Ar history
.Ar path
.Sh DESCRIPTION
.Nm
is not intended for manual use but rather by adding a line like
.Bd -literal -offset indent
t run "xterm" "-e" "tag-videos" "-c" "${working-directory}" "${path}"
.Ed
.Pp
to the
.Pa input.conf
configuration file of
.Xr mpv 1 .
.Pp
Options are as follows
.Bl -tag -width data
.It Fl c Ar cwd
Set
.Ar cwd
to which
.Ar path
will be relative, conforming to
.Xr mpv 1 Ns 's
running model.
.It Fl d Ar database
Select
.Ar database
instead of the default
.Pa $HOME/videos_tags .
.It Fl H Ar history
Select
.Ar history
file instead of the default
.Pa $HOME/.tag-videos-history .
.It Fl L
Don't resolve symlinks to absolute paths.
.It Fl q
Quit if tags are already defined.
.El
.Pp
This will open an interactive terminal with a few commands you can use
to manipulate tags on your videos.
.Pp
All tags are saved in an
.Xr sqlite3 1
database encoded as UTF-8 .
.Pp
Commands are as follows:
.Bl -tag -width suggestion -offset indent
.It Cm add Ar tag ...
Add
.Ar tag
to the current file.
.Po
But see
.Sh RULES
below.
.Pc
.It Cm descr
Edit the description for the current file,
using ${VISUAL} or ${EDIT} or
.Xr vi 1 .
.It Cm help
Show a summary of existing commands.
.It Cm known Op Ar partial
Show tags that contain the
.Ar partial
string.
.It Cm list
Show tags for the current file.
.It Cm quit
Quit.
.It Cm rm Ar tag ...
Remove
.Ar tag
from the current file.
.It Cm rename Ar old Ar new
Rename tag
.Ar old
into
.Ar new .
.It rmrule Ar partial
Delete permanent rules matching
.Ar partial
string .
.It Cm showrules
Show permanent rules associated with the database.
.It Cm suggest Ar tag ...
Show other tags that are mentioned with
.Ar tag ,
but not yet set on the current file, ordered by frequency.
.It Cm + Ar tag ...
Synonym for
.Cm add .
.It Cm q
Synonym for
.Cm quit .
.El
.Pp
Tags will be lowercased, and there might be restrictions on valid characters.
.Pp
.Nm
knows about already defined tags, so that completion works in the interface.
.Pp
Note that tags are committed on the fly: even if you don't quit
.Nm
properly, they will still be updated.
.Sh RULES
The database includes some limited programmable ability to set tags based
on other tags.
.Pp
The syntax is
.Bd -ragged -offset indent
.Oo ! Oc Ns Cm tag Ar t1 ... Cm IF Oo ! Oc Ns c1 ...
.Ed
.Pp
which will add the tag(s)
.Ar t1 ...
to any file which also features tag(s)
.Ar c1 ...
(or not if starting with a !).
.Pp
If the command starts with a !, then it is set as a permanent rule,
which will be saved in the database and executed on each exit from
.Nm .
.Sh ENVIRONMENT
.Bl -tag -width DBPATH
.It Ev DBPATH
Path to the database instead of the default
.Pa $HOME/video_tags
.It Ev LANG
.Nm
heeds locale information.
.El
.Sh FILES
.Bl -tag -width DBPATH
.It Pa $HOME/videos_tags
Default path to the
.Xr sqlite3 1
database .
.It Pa $HOME/.tag-videos-history
Default saved history file.
.El
.Sh SEE ALSO
.Xr display-videos-tags 1 ,
.Xr fix-videos-tags 1 ,
.Xr merge-videos-tags 1 ,
.Xr sqlite3 1 ,
.Xr search-video-tags 1
.Sh AUTHORS
.An Marc Espie
