#! /bin/sh

# Copyright (c) 2024 Marc Espie <espie@openbsd.org>
# 
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

cmd="sqlite3 -readonly ${DBPATH:=lib/mydb}"
query="select path from file join filetag on filetag.fileid=file.id"
subquery="select fileid from filetag join tag on tag.id=filetag.tagid"

connector=where
for i in $@
do
	query="$query $connector "
	connector=and
	not=
	case $i in
		!*) not=not; i=${i#!};;
	esac

	t=`echo select distinct 1 from filetag join tag on tag.id=filetag.tagid where tag=\'$i\'|$cmd`
	case $t in 
		1) s1="$subquery where tag='$i'";;
		*) s1="$subquery where tag like '%$i'";;
	esac
	query="$query fileid $not in ($s1)"
done

echo $query |$cmd
