.\" Copyright (c) 2024 Marc Espie <espie@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt VIEW-TAGS 1
.Os
.Sh NAME
.Nm view-tags
.Nd extract paths that contain some tags from the database
.Sh SYNOPSIS
.Nm view-tags
.Op Fl d Ar database
.Oo ! Oc Ns Ar tag ...
.Sh DESCRIPTION
Extract from the database all files that contain all the tags given
as
.Ar tag
and prints them to standard output.
.Pp
If a tag doesn't exist, the parameter will be used as a partial match,
.Pp
Prefixing a tag with ! will instead select files that do not contain this tag.
.Pp
.Nm
takes a single option:
.Fl d Ar database
to select another database instead of the default
.Pa $HOME/videos_tags .
.Sh ENVIRONMENT
.Bl -tag -width DBPATH
.It Ev DBPATH
Path to the database instead of the default
.Pa $HOME/video_tags
.El
.Sh SEE ALSO
.Xr tag-videos 1
.Sh AUTHORS
.An Marc Espie
