#! /bin/sh
db=lib/mydb
cmd="sqlite3 -readonly $db"
query="select path from file join filetag on filetag.fileid=file.id"
subquery="select fileid from filetag join tag on tag.id=filetag.tagid"

connector=where
for i in $@
do
	query="$query $connector "
	connector=and
	t=`echo select distinct 1 from filetag join tag on tag.id=filetag.tagid where tag=\'$i\'|$cmd`
	case $t in 
		1) s1="$subquery where tag='$i'";;
		*) s1="$subquery where tag like '%$i'";;
	esac
	query="$query fileid in ($s1)"
done

echo $query #|$cmd
