#! /bin/sh
cmd="sqlite3 -readonly ${DBPATH:=lib/mydb}"
query="select path from file join filetag on filetag.fileid=file.id"
subquery="select fileid from filetag join tag on tag.id=filetag.tagid"

connector=where
for i in $@
do
	query="$query $connector "
	connector=and
	not=
	case $i in
		!*) not=not; i=${i#!};;
	esac

	t=`echo select distinct 1 from filetag join tag on tag.id=filetag.tagid where tag=\'$i\'|$cmd`
	case $t in 
		1) s1="$subquery where tag='$i'";;
		*) s1="$subquery where tag like '%$i'";;
	esac
	query="$query fileid $not in ($s1)"
done

echo $query |$cmd
